CREATE  TABLE  prescriptions (
    id INT PRIMARY KEY AUTO_INCREMENT ,
    user_id INT NOT NULL ,
    next_checkup DATE NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);